---
abstract: 'build a Makefile.PL that uses ExtUtils::MakeMaker'
author:
  - 'Ævar Arnfjörð Bjarmason <avar@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-OverridableMakeMaker
no_index:
  directory:
    - t
requires:
  Data::Dumper: 0
  Dist::Zilla::File::InMemory: 0
  Dist::Zilla::Role::BuildRunner: 0
  Dist::Zilla::Role::FixedPrereqs: 0
  Dist::Zilla::Role::InstallTool: 0
  Dist::Zilla::Role::TestRunner: 0
  Dist::Zilla::Role::TextTemplate: 0
  List::MoreUtils: 0
  Moose: 0
  Moose::Autobox: 0
  Test::More: 0
  namespace::autoclean: 0
resources:
  Ratings: http://cpanratings.perl.org/d/Dist-Zilla-Plugin-OverridableMakeMaker
  bugtracker: http://github.com/avar/dist-zilla-plugin-overridablemakemaker/issues
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-OverridableMakeMaker/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/avar/dist-zilla-plugin-overridablemakemaker
version: 0.01
